pluginManagement {
    repositories {
        mavenLocal()
        maven { url = 'https://repo.huaweicloud.com/repository/maven/' }
        maven { url = 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        mavenCentral()
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net' }
    }
}

rootProject.name = 'examplemod'